### ISSUE TITLE
Namespace network isolation with Calico

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-iam/iam-infra#175]
Hey @The-smooth-operator and @ziegeer,

```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: deny-most
  namespace: prod
spec:
  selector: role != 'proxy'
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
    source:
      namespaceSelector: name == 'prod'
  - action: Deny
    source:
      namespaceSelector: name != 'prod'
  egress:
  - action: Allow
```

This policy should provide namespace network isolation. Sorry that got lost in the transition. Maybe it'll save you a little time. The policy can only be applied with `calicoctl` I believe. In order to do that, I had to run calicoctl as a pod in the cluster itself which is documented here:

https://docs.projectcalico.org/v3.5/usage/calicoctl/install#installing-calicoctl-as-a-kubernetes-pod

I think that the current cluster has Calico available in policy only mode but I'm not sure I fully understood the state of Calico in the cluster.

Cheers!
Daniel
